### ISSUE TITLE
[bug] blue bird is used but not listed in `package.json`

### ISSUE THREAD

**Issue by fa93hws** [appium/appium-xcode#129]
`bluebird` is used [here](https://github.com/appium/appium-xcode/blob/master/lib/helpers.js#L2) but only the type is listed in `package.json`, which won't work in pnpm.

**Comment by mykola-mokhnach** [comment]
Thanks for the report. Could you please create a PR and add the missing module?

**Comment by fa93hws** [comment]
No problem
