### ISSUE TITLE
Broken build

### ISSUE THREAD

**Issue by danhowitt** [appium/appium-xcode#14]
Any progress on fixing the broken build?
https://travis-ci.org/appium/appium-xcode

I seems '_.memoize' with retry is causing the issue. 

``` javascript
const getVersion = _.memoize(
  function (retries = DEFAULT_NUMBER_OF_RETRIES) {
    return retry(retries, getVersionWithoutRetry);
  }
);
```

Removing the retry call seems to work:

``` javascript
const getVersion = _.memoize(getVersionWithoutRetry);
```

**Comment by Jonahss** [comment]
Um, I think the tests marked with `@skip-linux` should be skipped. Since the travis machine is Linux.

**Comment by jlipps** [comment]
@Jonahss did you configure the CI to actually skip when it's on linux?

**Comment by Jonahss** [comment]
It probably isn't configured to skip them.

**Comment by danhowitt** [comment]
Guys, realise the the `@skip-linux` probably not being configured is causing the tests to fail on the CI box. I probably should have made myself more clear, the tests were failing on OSX. But it seems [2.0.5](https://github.com/appium/appium-xcode/releases/tag/v2.0.5) fixes the issue.

**Comment by sebv** [comment]
Yeah @sharky, that was an issue with the babeljs/regenerator dependencies, this should be fixed.
